// <auto-generated />
namespace Projekt_Przychodnia_TsWM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "202201231640114_Add-Events"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
